version: "3.1"

services:

  minio:
    image: minio/minio
    volumes:
      - billy-minio-data:/data
    ports:
      - "8080:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: ["server", "/data"]
    
volumes:
  billy-minio-data:
