version: '3.1'
services:
  
  minio:
    image: minio/minio
    volumes:
      - billy-integration-tests-minio-data:/data
    ports:
      - "8088:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: ["server", "/data"]
      
  db:
    image: postgres:12.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: temporarypassword
      POSTGRES_DB: billy
    ports:
      - "5433:5432"
    volumes:
      - billy-integration-tests-postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: "rabbitmq:3.7.3"
    hostname: billy-integration-tests-rabbitmq # required to persist data properly, Mnesia uses hostname in folder structure
    ports:
      - "5673:5672"
      - "15672:15671"
    volumes:
      - "./rabbitmq-config:/etc/rabbitmq"
      - "/rabbitmq:/var/lib/rabbitmq"
    restart: always

volumes:
  billy-integration-tests-minio-data:
  billy-integration-tests-postgres-data: