version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3.7.3"
    hostname: billy-rabbitmq # required to persist data properly, Mnesia uses hostname in folder structure
    ports:
      - "5672:5672"
      - "15671:15671"
    volumes:
      - "./rabbitmq-config:/etc/rabbitmq"
      - "/rabbitmq:/var/lib/rabbitmq"
    restart: always

