version: "3.1"

services:

  db:
     image: postgres:12.1
     restart: always
     environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: temporarypassword
       POSTGRES_DB: billy
     ports:
       - "5432:5432"
     volumes:
       - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
